import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NavBar } from "./components";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["500", "700"] });

export const metadata: Metadata = {
	title: "Shortly - More than just shorter links",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<NavBar />
				{children}
			</body>
		</html>
	);
}
